/* ============================================================
   AI Infrastructure Explorer — AUTO-GENERATED by ingest/generate_data_js.py
   Do NOT edit by hand; regenerated from ingest/store/*.json on each ingest.
   Single global: window.AIE_DATA. Load via <script src="data.js"> FIRST.
   ============================================================ */

window.AIE_DATA = {
  "meta": {
    "version": "1.0",
    "schemaVersion": 1,
    "lastUpdated": null,
    "source": "seed"
  },
  "countries": {
    "US": {
      "flag": "\ud83c\uddfa\ud83c\uddf8",
      "label": "United States"
    },
    "KR": {
      "flag": "\ud83c\uddf0\ud83c\uddf7",
      "label": "South Korea"
    },
    "TW": {
      "flag": "\ud83c\uddf9\ud83c\uddfc",
      "label": "Taiwan"
    },
    "SE": {
      "flag": "\ud83c\uddf8\ud83c\uddea",
      "label": "Sweden"
    },
    "FR": {
      "flag": "\ud83c\uddeb\ud83c\uddf7",
      "label": "France"
    },
    "DE": {
      "flag": "\ud83c\udde9\ud83c\uddea",
      "label": "Germany"
    }
  },
  "categories": {
    "photonics": {
      "id": "photonics",
      "label": "Photonics",
      "subtitle": "Optical Interconnects",
      "color": "#3b82f6",
      "layer": 3,
      "tooltip": "Light-based data transmission inside AI data centers. Copper cables cannot handle 100kW+ GPU rack bandwidth \u2014 optical interconnects replace them."
    },
    "memory": {
      "id": "memory",
      "label": "AI Memory",
      "subtitle": "HBM & DRAM",
      "color": "#8b5cf6",
      "layer": 2,
      "tooltip": "High-Bandwidth Memory (HBM) is physically stacked on top of NVDA GPUs. Every H100/B200 chip needs it. More AI training = more HBM demand."
    },
    "fabs": {
      "id": "fabs",
      "label": "Fabs & Foundries",
      "subtitle": "Chip Manufacturing",
      "color": "#f59e0b",
      "layer": 4,
      "tooltip": "The factories that physically manufacture chips. NVDA designs GPUs but does not make them \u2014 TSMC and others do the actual fabrication."
    },
    "neoclouds": {
      "id": "neoclouds",
      "label": "Neoclouds",
      "subtitle": "GPU Cloud Providers",
      "color": "#22c55e",
      "layer": 6,
      "tooltip": "New cloud companies built purely for AI GPU compute. They buy NVDA GPUs in bulk and rent compute time to AI startups and enterprises."
    },
    "materials": {
      "id": "materials",
      "label": "Materials & Packaging",
      "subtitle": "Substrates & Test",
      "color": "#f97316",
      "layer": 1,
      "tooltip": "Specialty substrates, wafer materials, and laser tools needed to build and package chips. The often-overlooked picks-and-shovels of AI."
    },
    "networking": {
      "id": "networking",
      "label": "Networking",
      "subtitle": "AI Cluster Connectivity",
      "color": "#14b8a6",
      "layer": 5,
      "tooltip": "InfiniBand and Ethernet fabric connecting thousands of GPUs into one coherent cluster. Without this, individual GPUs cannot work together at scale."
    }
  },
  "center": {
    "title": "NVIDIA + Hyperscalers",
    "subtitle": "GPU Designer & Buyers (MSFT, GOOGL, AMZN, META)",
    "tooltip": "NVIDIA designs the GPUs that power all AI training and inference. Every company in this map either supplies into NVDA chips, connects to them, or runs on top of them."
  },
  "tickers": [
    {
      "ticker": "AAOI",
      "company": "Applied Optoelectronics",
      "category": "photonics",
      "market": "US",
      "exchange": "NASDAQ",
      "whatTheyDo": "Makes optical transceivers that convert electrical signals into light pulses for high-speed data center connections.",
      "whyNVDA": "GPU racks at scale require optical links to move data fast enough between chips \u2014 copper cables physically cannot keep up at this bandwidth.",
      "marketCapTier": "Small",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "LITE",
      "company": "Lumentum Holdings",
      "category": "photonics",
      "market": "US",
      "exchange": "NASDAQ",
      "whatTheyDo": "Produces industrial lasers and optical components used inside data center transceivers and telecom equipment.",
      "whyNVDA": "Their laser components are inside the optical modules that connect NVDA GPU clusters across hyperscaler data centers.",
      "marketCapTier": "Mid",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "COHR",
      "company": "Coherent Corp",
      "category": "photonics",
      "market": "US",
      "exchange": "NYSE",
      "whatTheyDo": "Builds high-speed optical transceivers and laser components for AI data centers and telecommunications infrastructure.",
      "whyNVDA": "One of very few companies that can supply 400G/800G/1.6T optical modules at the volume AI infrastructure buildout demands.",
      "marketCapTier": "Large",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "SIVEF",
      "company": "Sivers Semiconductors AB",
      "category": "photonics",
      "market": "SE",
      "exchange": "Stockholm (OTC: SIVEF)",
      "whatTheyDo": "Swedish pure-play in silicon photonics, mmWave chips, and next-generation optical interconnects designed for AI data centers.",
      "whyNVDA": "Next-gen Co-Packaged Optics (CPO) \u2014 integrating optical directly onto chip packages \u2014 depends on silicon photonics specialists like Sivers.",
      "marketCapTier": "Small",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "MU",
      "company": "Micron Technology",
      "category": "memory",
      "market": "US",
      "exchange": "NASDAQ",
      "whatTheyDo": "US-based manufacturer of DRAM, NAND flash, and High-Bandwidth Memory (HBM) for AI accelerator chips.",
      "whyNVDA": "Every NVDA H100/H200/B200 GPU has HBM physically stacked on it \u2014 Micron is one of only 3 companies worldwide that can make it.",
      "marketCapTier": "Large",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "000660.KS",
      "company": "SK Hynix",
      "category": "memory",
      "market": "KR",
      "exchange": "KRX",
      "whatTheyDo": "South Korean memory giant and currently the world's leading supplier of HBM3 chips used in NVDA flagship AI GPUs.",
      "whyNVDA": "SK Hynix supplies the majority of HBM inside NVDA H100/H200 chips \u2014 arguably NVDA's single most critical supply chain partner right now.",
      "marketCapTier": "Mega",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "AXTI",
      "company": "AXT Inc",
      "category": "memory",
      "market": "US",
      "exchange": "NASDAQ",
      "whatTheyDo": "Makes compound semiconductor substrates \u2014 indium phosphide and gallium arsenide wafers used as the base for optical and RF chips.",
      "whyNVDA": "Their specialty wafer substrates are the foundation material for many photonic and high-frequency chips throughout the AI supply chain.",
      "marketCapTier": "Small",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "NVDA",
      "company": "NVIDIA Corporation",
      "category": "fabs",
      "market": "US",
      "exchange": "NASDAQ",
      "whatTheyDo": "Designs the world's most powerful AI GPUs (H100, H200, B200) and the CUDA software platform that runs all major AI models.",
      "whyNVDA": "NVDA IS the center of this entire map \u2014 every company here either supplies into NVDA chips, physically makes them, connects them, or builds on top of them.",
      "marketCapTier": "Mega",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "TSEM",
      "company": "Tower Semiconductor",
      "category": "fabs",
      "market": "US",
      "exchange": "NASDAQ",
      "whatTheyDo": "Israeli specialty analog and mixed-signal foundry that manufactures niche chips that large-scale foundries like TSMC will not produce.",
      "whyNVDA": "Produces analog, RF, and sensing chips \u2014 critical supporting components for photonics, power management, and AI infrastructure hardware.",
      "marketCapTier": "Mid",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "INTC",
      "company": "Intel Corporation",
      "category": "fabs",
      "market": "US",
      "exchange": "NASDAQ",
      "whatTheyDo": "Makes x86 CPUs and is building Intel Foundry Services (IFS) as a US-based alternative contract chip manufacturer to TSMC.",
      "whyNVDA": "Potential US-based alternative foundry for advanced chip packaging; also competes in AI accelerators with its Gaudi product line.",
      "marketCapTier": "Large",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "TSM",
      "company": "Taiwan Semiconductor Manufacturing Co",
      "category": "fabs",
      "market": "TW",
      "exchange": "TWSE (ADR: TSM)",
      "whatTheyDo": "The world's dominant contract chip foundry, manufacturing virtually every leading-edge chip including all NVIDIA GPU designs.",
      "whyNVDA": "NVDA is a fabless company \u2014 TSMC physically makes 100% of NVDA GPUs. No TSMC capacity = no NVIDIA chips, period.",
      "marketCapTier": "Mega",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "NBIS",
      "company": "Nebius Group",
      "category": "neoclouds",
      "market": "US",
      "exchange": "NASDAQ",
      "whatTheyDo": "European-origin GPU cloud provider building large-scale NVDA GPU clusters and renting AI compute capacity to developers and enterprises.",
      "whyNVDA": "Neoclouds are among NVDA's fastest-growing direct customer segment \u2014 they commit to large GPU orders and deploy them immediately.",
      "marketCapTier": "Mid",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "CRWV",
      "company": "CoreWeave Inc",
      "category": "neoclouds",
      "market": "US",
      "exchange": "NASDAQ",
      "whatTheyDo": "US-based neocloud operating massive NVDA GPU clusters, recently IPO'd, and one of NVDA's biggest revenue customers.",
      "whyNVDA": "CoreWeave has committed billions in NVDA GPU purchases \u2014 a direct, concentrated demand driver for NVDA data center revenue.",
      "marketCapTier": "Large",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "AEHR",
      "company": "Aehr Test Systems",
      "category": "materials",
      "market": "US",
      "exchange": "NASDAQ",
      "whatTheyDo": "Makes semiconductor wafer-level burn-in and test equipment used to stress-test and qualify chips before they ship to customers.",
      "whyNVDA": "As AI chips become more complex and expensive (H100 costs over $30K each), catching defects before deployment is critical \u2014 Aehr tools are used on advanced logic and silicon carbide chips.",
      "marketCapTier": "Small",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "SOI.PA",
      "company": "Soitec SA",
      "category": "materials",
      "market": "FR",
      "exchange": "Euronext Paris",
      "whatTheyDo": "French company that produces Silicon-on-Insulator (SOI) and specialty semiconductor wafers used in RF chips, photonics, and power devices.",
      "whyNVDA": "SOI wafers are used in RF and photonics chips throughout the AI supply chain \u2014 a materials-layer play on the photonics and advanced packaging buildout.",
      "marketCapTier": "Mid",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    },
    {
      "ticker": "LPK.DE",
      "company": "LPKF Laser & Electronics SE",
      "category": "materials",
      "market": "DE",
      "exchange": "Frankfurt",
      "whatTheyDo": "German company producing precision laser systems used to structure printed circuit boards and create the interconnect layers in advanced chip packaging substrates.",
      "whyNVDA": "NVDA chips use advanced CoWoS packaging from TSMC \u2014 the substrate layers in these packages require precision laser structuring tools like LPKF's systems.",
      "marketCapTier": "Small",
      "rating": "watch",
      "sourceTweetUrl": "",
      "addedDate": "2026-06-25"
    }
  ],
  "theses": [],
  "priorities": []
};
