"""Render data.js (window.AIE_DATA) from the JSON store.

SECURITY: every value is serialized with json.dumps, so any quotes,
</script>, or backticks inside ingested post text are escaped and cannot
break out of the data literal. ensure_ascii=True keeps data.js pure-ASCII,
which is the safest thing to ship over file:// across editors/encodings.
"""

import json
import pathlib

import scorer

ING = pathlib.Path(__file__).resolve().parent
STORE = ING / "store"
ROOT = ING.parent
DATA_JS = ROOT / "data.js"

HEADER = (
    "/* ============================================================\n"
    "   AI Infrastructure Explorer — AUTO-GENERATED by ingest/generate_data_js.py\n"
    "   Do NOT edit by hand; regenerated from ingest/store/*.json on each ingest.\n"
    "   Single global: window.AIE_DATA. Load via <script src=\"data.js\"> FIRST.\n"
    "   ============================================================ */\n"
)


def _load(name):
    return json.loads((STORE / name).read_text(encoding="utf-8"))


def _load_optional(name, default):
    path = STORE / name
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (ValueError, OSError):
        return default


PRICE_FIELDS = ("price", "currency", "chg7d", "chg1m", "marketCap", "asOf")


def build_data():
    """Assemble the AIE_DATA object from the store (no file write)."""
    base = _load("base.json")
    tickers = _load("tickers.json")
    theses = _load("theses.json")
    prices = _load_optional("prices.json", {})  # {ticker: {price, chg7d, chg1m, marketCap, asOf}}
    brain = _load_optional("brain.json", {})    # {} until synthesize.py has run; {meta, digests} after
    desk = _load_optional("verdicts.json", {})  # {} until the weekly desk review has run; {meta, verdicts} after

    # Merge weekly price snapshot (from fetch_prices.py) onto each ticker.
    for t in tickers:
        snap = prices.get(t["ticker"])
        if snap:
            for f in PRICE_FIELDS:
                if snap.get(f) is not None:
                    t[f] = snap[f]

    priorities = scorer.compute_priorities(theses)
    by_symbol = {p["ticker"]: p for p in priorities}
    for t in tickers:
        p = by_symbol.get(t["ticker"])
        if p and p["score"] > 0:
            t["priority"] = {
                "score": p["score"],
                "mentions": p["mentions"],
                "convictionHits": p["convictionHits"],
                "lastMentioned": p["lastMentioned"],
            }

    # Conviction tier (core/watch/radar) — drives default filtering in the app.
    tiers = scorer.assign_tiers([t["ticker"] for t in tickers], priorities)
    for t in tickers:
        t["tier"] = tiers[t["ticker"]]

    # Desk verdicts (Claude's weekly view) — stamped onto matching tickers so
    # the Watchlist/cards can render them without a join in the browser.
    verdict_by_symbol = {v["ticker"]: v for v in desk.get("verdicts", [])}
    for t in tickers:
        v = verdict_by_symbol.get(t["ticker"])
        if v:
            t["verdict"] = v

    categories = dict(base["categories"])
    if any(t.get("category") == "unsorted" for t in tickers):
        categories["unsorted"] = base["unsortedCategory"]

    return {
        "meta": base["meta"],
        "countries": base["countries"],
        "categories": categories,
        "center": base["center"],
        "mapIntro": base.get("mapIntro", ""),
        "glossary": base.get("glossary", []),
        "zones": base.get("zones", []),
        "tickers": tickers,
        "theses": theses,
        "priorities": priorities,
        "brain": brain,
        "desk": desk,
    }


def render(data):
    js = json.dumps(data, ensure_ascii=True, indent=2)
    # Defense-in-depth: escape angle brackets so a "</script>" inside post text
    # can never terminate a script tag (harmless for external src, but safe if
    # data.js is ever inlined). < / > decode back to the same string.
    js = js.replace("<", "\\u003c").replace(">", "\\u003e")
    return HEADER + "\nwindow.AIE_DATA = " + js + ";\n"


def write_data_js(data=None):
    data = data if data is not None else build_data()
    DATA_JS.write_text(render(data), encoding="utf-8")
    return DATA_JS


if __name__ == "__main__":
    path = write_data_js()
    print("Wrote", path)
