"""Render data.js (window.AIE_DATA) from the JSON store.

SECURITY: every value is serialized with json.dumps, so any quotes,
</script>, or backticks inside ingested post text are escaped and cannot
break out of the data literal. ensure_ascii=True keeps data.js pure-ASCII,
which is the safest thing to ship over file:// across editors/encodings.
"""

import json
import pathlib
import re
import xml.etree.ElementTree as ET

import scorer
import vault_sync

ING = pathlib.Path(__file__).resolve().parent
STORE = ING / "store"
ROOT = ING.parent
DATA_JS = ROOT / "data.js"

HEADER = (
    "/* ============================================================\n"
    "   AI Infrastructure Explorer — AUTO-GENERATED by ingest/generate_data_js.py\n"
    "   Do NOT edit by hand; regenerated from ingest/store/*.json on each ingest.\n"
    "   Single global: window.AIE_DATA. Load via <script src=\"data.js\"> FIRST.\n"
    "   ============================================================ */\n"
)


from store_io import load_json as _load, load_json_optional as _load_optional  # noqa: E402


PRICE_FIELDS = ("price", "currency", "chg7d", "chg1m", "chg1y", "marketCap", "asOf")

_ICON_ELEMENTS = {"path", "circle", "line", "rect", "polyline", "ellipse"}
_ICON_ATTRIBUTES = {
    "d", "cx", "cy", "r", "x", "y", "x1", "y1", "x2", "y2",
    "width", "height", "rx", "ry", "points", "fill", "stroke",
    "stroke-width", "stroke-linecap", "stroke-linejoin",
}


def _validate_icon(markup):
    """Reject unsafe or out-of-contract inner SVG markup from base.json.

    Icons are optional store data, but present markup is intentionally a tiny
    line-art subset before it reaches `innerHTML` in the browser.
    """
    if markup is None:
        return
    if not isinstance(markup, str):
        raise ValueError("icon markup must be a string")
    if re.search(r"<\s*/?\s*svg\b|<\s*script\b|\bhref\s*=|\bon\w+\s*=", markup, re.I):
        raise ValueError("icon markup contains a forbidden SVG construct")
    try:
        root = ET.fromstring("<icon>" + markup + "</icon>")
    except ET.ParseError as exc:
        raise ValueError("icon markup must be valid SVG fragment XML") from exc
    if root.text and root.text.strip():
        raise ValueError("icon markup cannot contain text")
    for node in root:
        if node.tag not in _ICON_ELEMENTS:
            raise ValueError("icon markup contains a disallowed element")
        if node.text and node.text.strip():
            raise ValueError("icon markup cannot contain text")
        if node.tail and node.tail.strip():
            raise ValueError("icon markup cannot contain text")
        if list(node):
            raise ValueError("icon markup cannot nest elements")
        if any(attr not in _ICON_ATTRIBUTES for attr in node.attrib):
            raise ValueError("icon markup contains a disallowed attribute")


def build_data():
    """Assemble the AIE_DATA object from the store (no file write)."""
    base = _load("base.json")
    tickers = _load("tickers.json")
    theses = _load("theses.json")
    prices = _load_optional("prices.json", {})  # {ticker: {price, chg7d, chg1m, marketCap, asOf}}
    brain = _load_optional("brain.json", {})    # {} until synthesize.py has run; {meta, digests} after
    desk = _load_optional("verdicts.json", {})  # {} until the weekly desk review has run; {meta, verdicts} after
    memos = _load_optional("memos.json", {})    # {} until authored; {meta, memos} after (coverage memos)
    vault = _load_optional("vault.json", {})    # {} until synced; {meta, pages} after (knowledge vault)
    calls = _load_optional("calls.json", {})    # {} until a first call is stamped; {meta, calls} after

    # Store-provided icon fragments are the only markup later assigned through
    # innerHTML. Validate every optional icon before it can reach data.js.
    for category in base.get("categories", {}).values():
        _validate_icon(category.get("icon"))
    _validate_icon((base.get("center") or {}).get("icon"))
    _validate_icon((base.get("unsortedCategory") or {}).get("icon"))

    # Merge weekly price snapshot (from fetch_prices.py) onto each ticker.
    for t in tickers:
        snap = prices.get(t["ticker"])
        if snap:
            for f in PRICE_FIELDS:
                if snap.get(f) is not None:
                    t[f] = snap[f]

    # Canonicalize symbols before counting (SIVEF -> SIVE; DRAM/SPCX are
    # theme tags, not tickers) so aliases don't split a name's mention count.
    canonical_theses = scorer.canonicalize_theses(
        theses, base.get("tickerAliases"), base.get("themeTags"))
    priorities = scorer.compute_priorities(canonical_theses)
    by_symbol = {p["ticker"]: p for p in priorities}
    for t in tickers:
        p = by_symbol.get(t["ticker"])
        if p and p["score"] > 0:
            t["priority"] = {
                "score": p["score"],
                "mentions": p["mentions"],
                "convictionHits": p["convictionHits"],
                "lastMentioned": p["lastMentioned"],
            }

    # Conviction tier (core/watch/radar) — drives default filtering in the app.
    tiers = scorer.assign_tiers([t["ticker"] for t in tickers], priorities)
    for t in tickers:
        t["tier"] = tiers[t["ticker"]]

    # Desk verdicts (Claude's weekly view) — stamped onto matching tickers so
    # the Watchlist/cards can render them without a join in the browser.
    verdict_by_symbol = {v["ticker"]: v for v in desk.get("verdicts", [])}
    for t in tickers:
        v = verdict_by_symbol.get(t["ticker"])
        if v:
            t["verdict"] = v

    categories = dict(base["categories"])
    if any(t.get("category") == "unsorted" for t in tickers):
        categories["unsorted"] = base["unsortedCategory"]

    return {
        "meta": base["meta"],
        "countries": base["countries"],
        "categories": categories,
        "center": base["center"],
        "mapIntro": base.get("mapIntro", ""),
        "glossary": base.get("glossary", []),
        "zones": base.get("zones", []),
        "tickers": tickers,
        "theses": theses,
        "priorities": priorities,
        "brain": brain,
        "desk": desk,
        "memos": memos,
        "vault": vault,
        "calls": calls,
        # Latest benchmark quote (fetched by fetch_prices.py alongside the
        # tickers) so performance.html can compute vs-SMH without a fetch().
        "benchmarkQuote": prices.get((calls.get("meta") or {}).get("benchmark", "SMH")) or None,
    }


def render(data):
    js = json.dumps(data, ensure_ascii=True, indent=2)
    # Defense-in-depth: escape angle brackets so a "</script>" inside post text
    # can never terminate a script tag (harmless for external src, but safe if
    # data.js is ever inlined). < / > decode back to the same string.
    js = js.replace("<", "\\u003c").replace(">", "\\u003e")
    return HEADER + "\nwindow.AIE_DATA = " + js + ";\n"


def write_data_js(data=None):
    if data is None:
        # Refresh the vault store from current tickers/tiers (preserving notes)
        # before assembling, so data.js always ships an up-to-date vault.
        vault_sync.sync()
        data = build_data()
    DATA_JS.write_text(render(data), encoding="utf-8")
    return DATA_JS


if __name__ == "__main__":
    path = write_data_js()
    print("Wrote", path)
